# Generated by Django 4.0.5 on 2022-06-07 17:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dbadmin',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
