# Generated by Django 4.0.5 on 2022-06-07 18:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0002_alter_dbadmin_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
            managers=[
                ('empBook_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
