# Generated by Django 4.0.5 on 2022-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstudent',
            name='fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dbstudent',
            name='lname',
            field=models.CharField(max_length=30),
        ),
    ]
